from typing import Any

class LockType:
    def acquire(self) -> Any: ...
    def locked(self) -> Any: ...
    def release(self) -> Any: ...

def allocate_lock() -> Any: ...
def exit() -> Any: ...
def get_ident() -> Any: ...
def stack_size() -> Any: ...
def start_new_thread() -> Any: ...
