from typing import Any

class APA106:
    ORDER: Any = ...
    def fill(self) -> Any: ...
    def write(self) -> Any: ...

class NeoPixel:
    ORDER: Any = ...
    def fill(self) -> Any: ...
    def write(self) -> Any: ...
