from typing import Any

def cos() -> Any: ...

e: float

def exp() -> Any: ...
def log() -> Any: ...
def log10() -> Any: ...
def phase() -> Any: ...

pi: float

def polar() -> Any: ...
def rect() -> Any: ...
def sin() -> Any: ...
def sqrt() -> Any: ...
