from typing import Any

class OrderedDict:
    def clear(self) -> Any: ...
    def copy(self) -> Any: ...
    def fromkeys(self) -> Any: ...
    def get(self) -> Any: ...
    def items(self) -> Any: ...
    def keys(self) -> Any: ...
    def pop(self) -> Any: ...
    def popitem(self) -> Any: ...
    def setdefault(self) -> Any: ...
    def update(self) -> Any: ...
    def values(self) -> Any: ...

class deque:
    def append(self) -> Any: ...
    def popleft(self) -> Any: ...

def namedtuple() -> Any: ...
