from typing import Any

class DHT11:
    def humidity(self) -> Any: ...
    def measure(self) -> Any: ...
    def temperature(self) -> Any: ...

class DHT22:
    def humidity(self) -> Any: ...
    def measure(self) -> Any: ...
    def temperature(self) -> Any: ...

class DHTBase:
    def measure(self) -> Any: ...

def dht_readinto() -> Any: ...
