from typing import Any

class DS18X20:
    def convert_temp(self) -> Any: ...
    def read_scratch(self) -> Any: ...
    def read_temp(self) -> Any: ...
    def scan(self) -> Any: ...
    def write_scratch(self) -> Any: ...

def const() -> Any: ...
