from typing import Any

LOG_DEBUG: int
LOG_ERROR: int
LOG_INFO: int
LOG_NONE: int
LOG_VERBOSE: int
LOG_WARNING: int

def dht_readinto() -> Any: ...
def flash_erase() -> Any: ...
def flash_read() -> Any: ...
def flash_size() -> Any: ...
def flash_user_start() -> Any: ...
def flash_write() -> Any: ...
def gpio_matrix_in() -> Any: ...
def gpio_matrix_out() -> Any: ...
def neopixel_write() -> Any: ...
def osdebug() -> Any: ...
