from typing import Any

HEAP_DATA: int
HEAP_EXEC: int

class NVS:
    def commit(self) -> Any: ...
    def erase_key(self) -> Any: ...
    def get_blob(self) -> Any: ...
    def get_i32(self) -> Any: ...
    def set_blob(self) -> Any: ...
    def set_i32(self) -> Any: ...

class Partition:
    BOOT: int = ...
    RUNNING: int = ...
    TYPE_APP: int = ...
    TYPE_DATA: int = ...
    def find(self) -> Any: ...
    def get_next_update(self) -> Any: ...
    def info(self) -> Any: ...
    def ioctl(self) -> Any: ...
    def mark_app_valid_cancel_rollback(self) -> Any: ...
    def readblocks(self) -> Any: ...
    def set_boot(self) -> Any: ...
    def writeblocks(self) -> Any: ...

class RMT:
    def clock_div(self) -> Any: ...
    def deinit(self) -> Any: ...
    def loop(self) -> Any: ...
    def source_freq(self) -> Any: ...
    def wait_done(self) -> Any: ...
    def write_pulses(self) -> Any: ...

class ULP:
    RESERVE_MEM: int = ...
    def load_binary(self) -> Any: ...
    def run(self) -> Any: ...
    def set_wakeup_period(self) -> Any: ...
WAKEUP_ALL_LOW = Any
WAKEUP_ANY_HIGH = Any

def hall_sensor() -> Any: ...
def idf_heap_info() -> Any: ...
def raw_temperature() -> Any: ...
def wake_on_ext0() -> Any: ...
def wake_on_ext1() -> Any: ...
def wake_on_touch() -> Any: ...
