from typing import Any

class Partition:
    BOOT: int = ...
    RUNNING: int = ...
    TYPE_APP: int = ...
    TYPE_DATA: int = ...
    def find(self) -> Any: ...
    def get_next_update(self) -> Any: ...
    def info(self) -> Any: ...
    def ioctl(self) -> Any: ...
    def mark_app_valid_cancel_rollback(self) -> Any: ...
    def readblocks(self) -> Any: ...
    def set_boot(self) -> Any: ...
    def writeblocks(self) -> Any: ...
bdev = Any
