from typing import Any

class FrameBuffer:
    def blit(self) -> Any: ...
    def fill(self) -> Any: ...
    def fill_rect(self) -> Any: ...
    def hline(self) -> Any: ...
    def line(self) -> Any: ...
    def pixel(self) -> Any: ...
    def rect(self) -> Any: ...
    def scroll(self) -> Any: ...
    def text(self) -> Any: ...
    def vline(self) -> Any: ...

def FrameBuffer1() -> Any: ...

GS2_HMSB: int
GS4_HMSB: int
GS8: int
MONO_HLSB: int
MONO_HMSB: int
MONO_VLSB: int
MVLSB: int
RGB565: int
