from typing import Any

def collect() -> Any: ...
def disable() -> Any: ...
def enable() -> Any: ...
def isenabled() -> Any: ...
def mem_alloc() -> Any: ...
def mem_free() -> Any: ...
def threshold() -> Any: ...
