from typing import Any

CRITICAL: int
DEBUG: int
ERROR: int
INFO: int

class Logger:
    def _level_str(self) -> Any: ...
    def critical(self) -> Any: ...
    def debug(self) -> Any: ...
    def error(self) -> Any: ...
    def exc(self) -> Any: ...
    def exception(self) -> Any: ...
    def info(self) -> Any: ...
    def isEnabledFor(self) -> Any: ...
    level: int = ...
    def log(self) -> Any: ...
    def setLevel(self) -> Any: ...
    def warning(self) -> Any: ...

NOTSET: int
WARNING: int
_level: int
_level_dict = Any
_loggers = Any
_stream = Any

def basicConfig() -> Any: ...
def debug() -> Any: ...
def getLogger() -> Any: ...
def info() -> Any: ...
sys = Any
