from typing import Any

def acos() -> Any: ...
def acosh() -> Any: ...
def asin() -> Any: ...
def asinh() -> Any: ...
def atan() -> Any: ...
def atan2() -> Any: ...
def atanh() -> Any: ...
def ceil() -> Any: ...
def copysign() -> Any: ...
def cos() -> Any: ...
def cosh() -> Any: ...
def degrees() -> Any: ...

e: float

def erf() -> Any: ...
def erfc() -> Any: ...
def exp() -> Any: ...
def expm1() -> Any: ...
def fabs() -> Any: ...
def floor() -> Any: ...
def fmod() -> Any: ...
def frexp() -> Any: ...
def gamma() -> Any: ...
def isclose() -> Any: ...
def isfinite() -> Any: ...
def isinf() -> Any: ...
def isnan() -> Any: ...
def ldexp() -> Any: ...
def lgamma() -> Any: ...
def log() -> Any: ...
def log10() -> Any: ...
def log2() -> Any: ...
def modf() -> Any: ...

pi: float

def pow() -> Any: ...
def radians() -> Any: ...
def sin() -> Any: ...
def sinh() -> Any: ...
def sqrt() -> Any: ...
def tan() -> Any: ...
def tanh() -> Any: ...
def trunc() -> Any: ...
