from typing import Any

def alloc_emergency_exception_buf() -> Any: ...
def const() -> Any: ...
def heap_lock() -> Any: ...
def heap_unlock() -> Any: ...
def kbd_intr() -> Any: ...
def mem_info() -> Any: ...
def opt_level() -> Any: ...
def qstr_info() -> Any: ...
def schedule() -> Any: ...
def stack_use() -> Any: ...
