from typing import Any

class OneWire:
    MATCH_ROM: int = ...
    SEARCH_ROM: int = ...
    SKIP_ROM: int = ...
    def _search_rom(self) -> Any: ...
    def crc8(self) -> Any: ...
    def readbit(self) -> Any: ...
    def readbyte(self) -> Any: ...
    def readinto(self) -> Any: ...
    def reset(self) -> Any: ...
    def scan(self) -> Any: ...
    def select_rom(self) -> Any: ...
    def write(self) -> Any: ...
    def writebit(self) -> Any: ...
    def writebyte(self) -> Any: ...

class OneWireError: ...
_ow = Any
