from typing import Any

class VfsFat:
    def chdir(self) -> Any: ...
    def getcwd(self) -> Any: ...
    def ilistdir(self) -> Any: ...
    def mkdir(self) -> Any: ...
    def mkfs(self) -> Any: ...
    def mount(self) -> Any: ...
    def open(self) -> Any: ...
    def remove(self) -> Any: ...
    def rename(self) -> Any: ...
    def rmdir(self) -> Any: ...
    def stat(self) -> Any: ...
    def statvfs(self) -> Any: ...
    def umount(self) -> Any: ...

class VfsLfs2:
    def chdir(self) -> Any: ...
    def getcwd(self) -> Any: ...
    def ilistdir(self) -> Any: ...
    def mkdir(self) -> Any: ...
    def mkfs(self) -> Any: ...
    def mount(self) -> Any: ...
    def open(self) -> Any: ...
    def remove(self) -> Any: ...
    def rename(self) -> Any: ...
    def rmdir(self) -> Any: ...
    def stat(self) -> Any: ...
    def statvfs(self) -> Any: ...
    def umount(self) -> Any: ...

def chdir() -> Any: ...
def dupterm() -> Any: ...
def dupterm_notify() -> Any: ...
def getcwd() -> Any: ...
def ilistdir() -> Any: ...
def listdir() -> Any: ...
def mkdir() -> Any: ...
def mount() -> Any: ...
def remove() -> Any: ...
def rename() -> Any: ...
def rmdir() -> Any: ...
def stat() -> Any: ...
def statvfs() -> Any: ...
def umount() -> Any: ...
def uname() -> Any: ...
def urandom() -> Any: ...
