from typing import Any

class BLE:
    def active(self) -> Any: ...
    def config(self) -> Any: ...
    def gap_advertise(self) -> Any: ...
    def gap_connect(self) -> Any: ...
    def gap_disconnect(self) -> Any: ...
    def gap_scan(self) -> Any: ...
    def gattc_discover_characteristics(self) -> Any: ...
    def gattc_discover_descriptors(self) -> Any: ...
    def gattc_discover_services(self) -> Any: ...
    def gattc_exchange_mtu(self) -> Any: ...
    def gattc_read(self) -> Any: ...
    def gattc_write(self) -> Any: ...
    def gatts_indicate(self) -> Any: ...
    def gatts_notify(self) -> Any: ...
    def gatts_read(self) -> Any: ...
    def gatts_register_services(self) -> Any: ...
    def gatts_set_buffer(self) -> Any: ...
    def gatts_write(self) -> Any: ...
    def irq(self) -> Any: ...

FLAG_INDICATE: int
FLAG_NOTIFY: int
FLAG_READ: int
FLAG_WRITE: int
FLAG_WRITE_NO_RESPONSE: int

class UUID: ...
