from typing import Any

class BufferedWriter:
    def flush(self) -> Any: ...
    def write(self) -> Any: ...

class BytesIO:
    def close(self) -> Any: ...
    def flush(self) -> Any: ...
    def getvalue(self) -> Any: ...
    def read(self) -> Any: ...
    def readinto(self) -> Any: ...
    def readline(self) -> Any: ...
    def seek(self) -> Any: ...
    def tell(self) -> Any: ...
    def write(self) -> Any: ...

class FileIO:
    def close(self) -> Any: ...
    def flush(self) -> Any: ...
    def read(self) -> Any: ...
    def readinto(self) -> Any: ...
    def readline(self) -> Any: ...
    def readlines(self) -> Any: ...
    def seek(self) -> Any: ...
    def tell(self) -> Any: ...
    def write(self) -> Any: ...

class IOBase: ...

class StringIO:
    def close(self) -> Any: ...
    def flush(self) -> Any: ...
    def getvalue(self) -> Any: ...
    def read(self) -> Any: ...
    def readinto(self) -> Any: ...
    def readline(self) -> Any: ...
    def seek(self) -> Any: ...
    def tell(self) -> Any: ...
    def write(self) -> Any: ...

class TextIOWrapper:
    def close(self) -> Any: ...
    def flush(self) -> Any: ...
    def read(self) -> Any: ...
    def readinto(self) -> Any: ...
    def readline(self) -> Any: ...
    def readlines(self) -> Any: ...
    def seek(self) -> Any: ...
    def tell(self) -> Any: ...
    def write(self) -> Any: ...

def open() -> Any: ...
