from typing import Any

class NotFoundError: ...

def _makedirs() -> Any: ...
def cleanup() -> Any: ...
cleanup_files = Any
debug = Any
errno = Any

def expandhome() -> Any: ...
def fatal() -> Any: ...
file_buf = Any
gc = Any

def get_install_path() -> Any: ...
def get_pkg_metadata() -> Any: ...

gzdict_sz: int

def help() -> Any: ...
index_urls = Any

def install() -> Any: ...
install_path = Any

def install_pkg() -> Any: ...
def install_tar() -> Any: ...
json = Any

def main() -> Any: ...
def op_basename() -> Any: ...
def op_split() -> Any: ...
os = Any

def save_file() -> Any: ...
sys = Any
tarfile = Any

def url_open() -> Any: ...
usocket = Any
ussl = Any
uzlib = Any
warn_ussl = Any
