from typing import Any

DIRTYPE: str

class FileSection:
    def read(self) -> Any: ...
    def readinto(self) -> Any: ...
    def skip(self) -> Any: ...

REGTYPE: str
TAR_HEADER = Any

class TarFile:
    def extractfile(self) -> Any: ...
    def next(self) -> Any: ...

class TarInfo: ...

def roundup() -> Any: ...
uctypes = Any
