from typing import Any

def choice() -> Any: ...
def getrandbits() -> Any: ...
def randint() -> Any: ...
def random() -> Any: ...
def randrange() -> Any: ...
def seed() -> Any: ...
def uniform() -> Any: ...
