from typing import Any

AF_INET: int
AF_INET6: int
IPPROTO_IP: int
IPPROTO_TCP: int
IPPROTO_UDP: int
IP_ADD_MEMBERSHIP: int
SOCK_DGRAM: int
SOCK_RAW: int
SOCK_STREAM: int
SOL_SOCKET: int
SO_REUSEADDR: int

def getaddrinfo() -> Any: ...

class socket:
    def accept(self) -> Any: ...
    def bind(self) -> Any: ...
    def close(self) -> Any: ...
    def connect(self) -> Any: ...
    def fileno(self) -> Any: ...
    def listen(self) -> Any: ...
    def makefile(self) -> Any: ...
    def read(self) -> Any: ...
    def readinto(self) -> Any: ...
    def readline(self) -> Any: ...
    def recv(self) -> Any: ...
    def recvfrom(self) -> Any: ...
    def send(self) -> Any: ...
    def sendall(self) -> Any: ...
    def sendto(self) -> Any: ...
    def setblocking(self) -> Any: ...
    def setsockopt(self) -> Any: ...
    def settimeout(self) -> Any: ...
    def write(self) -> Any: ...
