from typing import Any

def gmtime() -> Any: ...
def localtime() -> Any: ...
def mktime() -> Any: ...
def sleep() -> Any: ...
def sleep_ms() -> Any: ...
def sleep_us() -> Any: ...
def ticks_add() -> Any: ...
def ticks_cpu() -> Any: ...
def ticks_diff() -> Any: ...
def ticks_ms() -> Any: ...
def ticks_us() -> Any: ...
def time() -> Any: ...
def time_ns() -> Any: ...
