from typing import Any

class websocket:
    def close(self) -> Any: ...
    def ioctl(self) -> Any: ...
    def read(self) -> Any: ...
    def readinto(self) -> Any: ...
    def readline(self) -> Any: ...
    def write(self) -> Any: ...
