from typing import Any

class OneWireError(Exception): ...

class OneWire:
    SEARCH_ROM: int = ...
    MATCH_ROM: int = ...
    SKIP_ROM: int = ...
    pin: Any = ...
    def __init__(self, pin: Any) -> None: ...
    def reset(self, required: bool=...) -> Any: ...
    def readbit(self) -> None: ...
    def readbyte(self) -> None: ...
    def readinto(self, buf: Any) -> None: ...
    def writebit(self, value: Any) -> Any: ...
    def writebyte(self, value: Any) -> Any: ...
    def write(self, buf: Any) -> None: ...
    def select_rom(self, rom: Any) -> None: ...
    def scan(self) -> None: ...
    def _search_rom(self, l_rom: Any, diff: Any) -> Any: ...
    def crc8(self, data: Any) -> Any: ...
