from typing import Any

def compile(pattern: Any, flags: int=...) -> Any: ...
def match(pattern: Any, string: Any) -> Any: ...
def search(pattern: Any, string: Any) -> Any: ...
def sub(pattern: Any, repl: Any, string: Any, count: int=..., flags: int=...) -> Any: ...
