from typing import Any, Optional

POLLIN: Any
POLLOUT: Any

class poll:
    sel: Any = ...
    def __init__(self) -> None: ...
    def register(self, stream: Any, events: Any, userdata: Optional[Any]=...) -> Any: ...
    def ipoll(self, timeout: int=...) -> None: ...
