from typing import Any

class Entry:
    time: Any = ...
    obj: Any = ...
    userdata: Any = ...
    def __init__(self, time: Any, obj: Any, userdata: Any) -> None: ...
    def __lt__(self, another: Any) -> Any: ...

class utimeq:
    heap: Any = ...
    max_sz: Any = ...
    def __init__(self, sz: Any) -> None: ...
    def __bool__(self) -> None: ...
    def push(self, time: Any, obj: Any, userdata: Any) -> Any: ...
    def pop(self, arr: Any) -> None: ...
    def peektime(self) -> None: ...
    def remove(self, id: Any) -> None: ...
