from zlib import *
from typing import Any, Optional

class DecompIO:
    stream: Any = ...
    decomp: Any = ...
    pending: bytes = ...
    def __init__(self, stream: Any, dict_bits: Any, dictbuf: Optional[Any]=...) -> None: ...
    def read(self, size: Any) -> Any: ...
