from typing import Any

class Calc:
    def __init__(self, *args: Any) -> None: ...
    def _available() -> None: ...
    def _update() -> None: ...
    def clearStr() -> None: ...
    def deinit() -> None: ...
    def deleteStrLast() -> None: ...
    def isNewKeyPress() -> None: ...
    def readKey() -> None: ...
    def readStr() -> None: ...

i2c_bus: Any
