from typing import Any

class Joystick:
    def __init__(self, *args: Any) -> None: ...
    InvertX: Any = ...
    InvertY: Any = ...
    Press: Any = ...
    X: Any = ...
    Y: Any = ...
    def _available() -> None: ...
    def _update() -> None: ...
    def deinit() -> None: ...
    def setLed() -> None: ...

i2c_bus: Any
time: Any
