from typing import Any

START_HEADER_SIZE: int
LED_START: int
RGB: Any
RBG: Any
GRB: Any
GBR: Any
BRG: Any
BGR: Any

class DotStar:
    _spi: Any = ...
    _n: Any = ...
    end_header_size: Any = ...
    _buf: Any = ...
    end_header_index: Any = ...
    pixel_order: Any = ...
    _brightness: float = ...
    auto_write: bool = ...
    def __init__(self, spi: Any, n: Any, *, brightness: float=..., auto_write: bool=..., pixel_order: Any=...) -> None: ...
    def deinit(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exception_type: Any, exception_value: Any, traceback: Any) -> None: ...
    def __repr__(self) -> None: ...
    def _set_item(self, index: Any, value: Any) -> None: ...
    def __setitem__(self, index: Any, val: Any) -> None: ...
    def __getitem__(self, index: Any) -> Any: ...
    def __len__(self) -> None: ...
    @property
    def brightness(self) -> None: ...
    @brightness.setter
    def brightness(self, brightness: Any) -> None: ...
    def fill(self, color: Any) -> None: ...
    def show(self) -> None: ...
