from typing import Any, Optional

class Response:
    raw: Any = ...
    encoding: str = ...
    _cached: Any = ...
    def __init__(self, f: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def content(self): ...
    @property
    def text(self): ...
    def json(self): ...

def request(method: Any, url: Any, data: Optional[Any] = ..., json: Optional[Any] = ..., headers: Any = ..., stream: Optional[Any] = ...): ...
def head(url: Any, **kw: Any): ...
def get(url: Any, **kw: Any): ...
def post(url: Any, **kw: Any): ...
def put(url: Any, **kw: Any): ...
def patch(url: Any, **kw: Any): ...
def delete(url: Any, **kw: Any): ...
