from typing import Any

RC: str
CONFIG: str

def input_choice(prompt: Any, choices: Any): ...
def getpass(prompt: Any): ...
def input_pass(): ...
def exists(fname: Any): ...
def get_daemon_status(): ...
def change_daemon(action: Any) -> None: ...
def main() -> None: ...
