from typing import Any, Tuple

Node = Any

class AK8963:
    def __init__(self, i2c: Any, address: Any=..., mode: Any=..., output: Any=..., offset: Any=..., scale: Any=...) -> None: ...
    def magnetic(self) -> Tuple[Any]: ...
    def adjustement(self) -> Any: ...
    def whoami(self) -> Any: ...
    def _register_short(self, register: Any, value: Any=..., buf: Any=...) -> Any: ...
    def _register_three_shorts(self, register: Any, buf: Any=...) -> Any: ...
    def _register_char(self, register: Any, value: Any=..., buf: Any=...) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exception_type: Any, exception_value: Any, traceback: Any) -> None: ...
