from typing import Any, Tuple

Node = Any

def height() -> number: ...
def max_width() -> number: ...
def hmap() -> bool: ...
def reverse() -> bool: ...
def monospaced() -> bool: ...
def min_ch() -> number: ...
def max_ch() -> number: ...
def _chr_addr(ordch: Any) -> Any: ...
def get_ch(ch: Any) -> Tuple[Any, number, Any]: ...
