from typing import Any, Union

Node = Any

class Logger:
    def __init__(self, name: str) -> None: ...
    def _level_str(self, level: Any) -> Union[Any, str]: ...
    def setLevel(self, level: Any) -> None: ...
    def isEnabledFor(self, level: Any) -> bool: ...
    def log(self, level: Any, msg: Any, *args: Any) -> None: ...
    def debug(self, msg: Any, *args: Any) -> None: ...
    def info(self, msg: Any, *args: Any) -> None: ...
    def warning(self, msg: Any, *args: Any) -> None: ...
    def error(self, msg: Any, *args: Any) -> None: ...
    def critical(self, msg: Any, *args: Any) -> None: ...
    def exc(self, e: Any, msg: Any, *args: Any) -> None: ...
    def exception(self, msg: Any, *args: Any) -> None: ...

def getLogger(name: str) -> Any: ...
def info(msg: Any, *args: Any) -> None: ...
def debug(msg: Any, *args: Any) -> None: ...
def basicConfig(level: Any=..., filename: str=..., stream: Any=..., format: Any=...) -> None: ...
