from typing import Any, Optional, Union

Node = Any

class MicroWebSocket:
    def _tryAllocByteArray(size: Any) -> Optional[Any]: ...
    def _tryStartThread(func: Any, args: Any=..., stackSize: Any=...) -> Union[Any, bool]: ...
    def __init__(self, socket: Any, httpClient: Any, httpResponse: Any, maxRecvLen: Any, threaded: Any, acceptCallback: Any, stackSize: Any=...) -> None: ...
    def _handshake(self, httpResponse: Any) -> bool: ...
    def _wsProcess(self, acceptCallback: Any) -> None: ...
    def _receiveFrame(self) -> bool: ...
    def _sendFrame(self, opcode: Any, data: Any=..., fin: Any=...) -> Union[Any, bool]: ...
    def SendText(self, msg: Any) -> Any: ...
    def SendBinary(self, data: Any) -> Any: ...
    def IsClosed(self) -> Any: ...
    def threadID(self) -> Any: ...
    def Close(self) -> None: ...
