from typing import Any

Node = Any

class MPU9250:
    def __init__(self, i2c: Any, mpu6500: Any=..., ak8963: Any=...) -> None: ...
    def acceleration(self) -> Any: ...
    def gyro(self) -> Any: ...
    def magnetic(self) -> Any: ...
    def whoami(self) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exception_type: Any, exception_value: Any, traceback: Any) -> None: ...
