from typing import Any, Tuple, Union

Node = Any

class NotFoundError(Exception): ...

def op_split(path: Any) -> Union[Tuple[Any, str], Tuple[str, Any], Tuple[str, str]]: ...
def op_basename(path: Any) -> Any: ...
def _makedirs(name: str, mode: Any=...) -> Any: ...
def save_file(fname: Any, subf: Any) -> None: ...
def install_tar(f: Any, prefix: Any) -> Any: ...
def expandhome(s: str) -> str: ...
def url_open(url: Any) -> str: ...
def get_pkg_metadata(name: str) -> Any: ...
def fatal(msg: Any, exc: Any=...) -> None: ...
def install_pkg(pkg_spec: Any, install_path: Any) -> Any: ...
def install(to_install: Any, install_path: Any=...) -> None: ...
def get_install_path() -> Any: ...
def cleanup() -> None: ...
def help() -> None: ...
def main() -> None: ...
