from typing import Any

class ArithmeticError: ...
class AssertionError: ...
class AttributeError: ...
class BaseException: ...
class EOFError: ...

Ellipsis: Any

class Exception:
    def __init__(self, *args: Any) -> None: ...

class GeneratorExit:
    def __init__(self, *args: Any) -> None: ...

class ImportError: ...
class IndentationError: ...
class IndexError: ...
class KeyError: ...

class KeyboardInterrupt:
    def __init__(self, *args: Any) -> None: ...

class LookupError: ...
class MemoryError: ...
class NameError: ...

NotImplemented: Any

class NotImplementedError: ...
class OSError: ...
class OverflowError: ...
class RuntimeError: ...

class StopAsyncIteration:
    def __init__(self, *args: Any) -> None: ...

class StopIteration:
    def __init__(self, *args: Any) -> None: ...

class SyntaxError: ...

class SystemExit:
    def __init__(self, *args: Any) -> None: ...

class TypeError: ...
class UnicodeError: ...
class ValueError: ...
class ZeroDivisionError: ...

def abs() -> None: ...
def all() -> None: ...
def any() -> None: ...
def bin() -> None: ...

class bool:
    def __init__(self, *args: Any) -> None: ...

class bytearray:
    def __init__(self, *args: Any) -> None: ...
    def append() -> None: ...
    def decode() -> None: ...
    def extend() -> None: ...

class bytes:
    def __init__(self, *args: Any) -> None: ...
    def center() -> None: ...
    def count() -> None: ...
    def decode() -> None: ...
    def endswith() -> None: ...
    def find() -> None: ...
    def format() -> None: ...
    def index() -> None: ...
    def isalpha() -> None: ...
    def isdigit() -> None: ...
    def islower() -> None: ...
    def isspace() -> None: ...
    def isupper() -> None: ...
    def join() -> None: ...
    def lower() -> None: ...
    def lstrip() -> None: ...
    def partition() -> None: ...
    def replace() -> None: ...
    def rfind() -> None: ...
    def rindex() -> None: ...
    def rpartition() -> None: ...
    def rsplit() -> None: ...
    def rstrip() -> None: ...
    def split() -> None: ...
    def splitlines() -> None: ...
    def startswith() -> None: ...
    def strip() -> None: ...
    def upper() -> None: ...

def callable() -> None: ...
def chr() -> None: ...

class classmethod:
    def __init__(self, *args: Any) -> None: ...

def compile() -> None: ...

class complex:
    def __init__(self, *args: Any) -> None: ...

def delattr() -> None: ...

class dict:
    def __init__(self, *args: Any) -> None: ...
    def clear() -> None: ...
    def copy() -> None: ...
    def fromkeys() -> None: ...
    def get() -> None: ...
    def items() -> None: ...
    def keys() -> None: ...
    def pop() -> None: ...
    def popitem() -> None: ...
    def setdefault() -> None: ...
    def update() -> None: ...
    def values() -> None: ...

def dir() -> None: ...
def divmod() -> None: ...

class enumerate:
    def __init__(self, *args: Any) -> None: ...

def eval() -> None: ...
def exec() -> None: ...
def execfile() -> None: ...

class filter:
    def __init__(self, *args: Any) -> None: ...

class float:
    def __init__(self, *args: Any) -> None: ...

class frozenset:
    def __init__(self, *args: Any) -> None: ...
    def copy() -> None: ...
    def difference() -> None: ...
    def intersection() -> None: ...
    def isdisjoint() -> None: ...
    def issubset() -> None: ...
    def issuperset() -> None: ...
    def symmetric_difference() -> None: ...
    def union() -> None: ...

def getattr() -> None: ...
def globals() -> None: ...
def hasattr() -> None: ...
def hash() -> None: ...
def help() -> None: ...
def hex() -> None: ...
def id() -> None: ...
def input() -> None: ...

class int:
    def __init__(self, *args: Any) -> None: ...
    def from_bytes() -> None: ...
    def to_bytes() -> None: ...

def isinstance() -> None: ...
def issubclass() -> None: ...
def iter() -> None: ...
def len() -> None: ...

class list:
    def __init__(self, *args: Any) -> None: ...
    def append() -> None: ...
    def clear() -> None: ...
    def copy() -> None: ...
    def count() -> None: ...
    def extend() -> None: ...
    def index() -> None: ...
    def insert() -> None: ...
    def pop() -> None: ...
    def remove() -> None: ...
    def reverse() -> None: ...
    def sort() -> None: ...

def locals() -> None: ...

class map:
    def __init__(self, *args: Any) -> None: ...

def max() -> None: ...

class memoryview:
    def __init__(self, *args: Any) -> None: ...

def min() -> None: ...
def next() -> None: ...

class object:
    def __init__(self, *args: Any) -> None: ...

def oct() -> None: ...
def open() -> None: ...
def ord() -> None: ...
def pow() -> None: ...
def print() -> None: ...

class property:
    def __init__(self, *args: Any) -> None: ...
    def deleter() -> None: ...
    def getter() -> None: ...
    def setter() -> None: ...

class range:
    def __init__(self, *args: Any) -> None: ...

def repr() -> None: ...

class reversed:
    def __init__(self, *args: Any) -> None: ...

def round() -> None: ...

class set:
    def __init__(self, *args: Any) -> None: ...
    def add() -> None: ...
    def clear() -> None: ...
    def copy() -> None: ...
    def difference() -> None: ...
    def difference_update() -> None: ...
    def discard() -> None: ...
    def intersection() -> None: ...
    def intersection_update() -> None: ...
    def isdisjoint() -> None: ...
    def issubset() -> None: ...
    def issuperset() -> None: ...
    def pop() -> None: ...
    def remove() -> None: ...
    def symmetric_difference() -> None: ...
    def symmetric_difference_update() -> None: ...
    def union() -> None: ...
    def update() -> None: ...

def setattr() -> None: ...

class slice:
    def __init__(self, *args: Any) -> None: ...

def sorted() -> None: ...

class staticmethod:
    def __init__(self, *args: Any) -> None: ...

class str:
    def __init__(self, *args: Any) -> None: ...
    def center() -> None: ...
    def count() -> None: ...
    def encode() -> None: ...
    def endswith() -> None: ...
    def find() -> None: ...
    def format() -> None: ...
    def index() -> None: ...
    def isalpha() -> None: ...
    def isdigit() -> None: ...
    def islower() -> None: ...
    def isspace() -> None: ...
    def isupper() -> None: ...
    def join() -> None: ...
    def lower() -> None: ...
    def lstrip() -> None: ...
    def partition() -> None: ...
    def replace() -> None: ...
    def rfind() -> None: ...
    def rindex() -> None: ...
    def rpartition() -> None: ...
    def rsplit() -> None: ...
    def rstrip() -> None: ...
    def split() -> None: ...
    def splitlines() -> None: ...
    def startswith() -> None: ...
    def strip() -> None: ...
    def upper() -> None: ...

def sum() -> None: ...

class super:
    def __init__(self, *args: Any) -> None: ...

class tuple:
    def __init__(self, *args: Any) -> None: ...
    def count() -> None: ...
    def index() -> None: ...

class type:
    def __init__(self, *args: Any) -> None: ...

class zip:
    def __init__(self, *args: Any) -> None: ...
