from typing import Any

class M5Button:
    def __init__(self, *args: Any) -> None: ...

class M5Circle:
    def __init__(self, *args: Any) -> None: ...
    def hide() -> None: ...
    def setBgColor() -> None: ...
    def setBorderColor() -> None: ...
    def setPosition() -> None: ...
    def setSize() -> None: ...
    def show() -> None: ...

class M5Img:
    def __init__(self, *args: Any) -> None: ...
    def changeImg() -> None: ...
    def hide() -> None: ...
    def setPosition() -> None: ...
    def show() -> None: ...

class M5Rect:
    def __init__(self, *args: Any) -> None: ...
    def hide() -> None: ...
    def setBgColor() -> None: ...
    def setBorderColor() -> None: ...
    def setPosition() -> None: ...
    def setSize() -> None: ...
    def show() -> None: ...

class M5TextBox:
    def __init__(self, *args: Any) -> None: ...
    def hide() -> None: ...
    def setColor() -> None: ...
    def setFont() -> None: ...
    def setPosition() -> None: ...
    def setRotate() -> None: ...
    def setText() -> None: ...
    def show() -> None: ...

class M5Title:
    def __init__(self, *args: Any) -> None: ...
    def hide() -> None: ...
    def setBgColor() -> None: ...
    def setFgColor() -> None: ...
    def setTitle() -> None: ...
    def show() -> None: ...

def M5UI_Deinit() -> None: ...
def setScreenColor() -> None: ...
