from typing import Any

class NeoPixel:
    def __init__(self, *args: Any) -> None: ...
    ORDER: Any = ...
    def fill() -> None: ...
    def write() -> None: ...

def neopixel_write() -> None: ...
