from typing import Any

class sha1:
    def __init__(self, *args: Any) -> None: ...
    def digest() -> None: ...
    def update() -> None: ...

class sha256:
    def __init__(self, *args: Any) -> None: ...
    def digest() -> None: ...
    def update() -> None: ...
