from typing import Any

DIRTYPE: str

class FileSection:
    def __init__(self, *args: Any) -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def skip() -> None: ...

REGTYPE: str
TAR_HEADER: Any

class TarFile:
    def __init__(self, *args: Any) -> None: ...
    def extractfile() -> None: ...
    def next() -> None: ...

class TarInfo:
    def __init__(self, *args: Any) -> None: ...

def roundup() -> None: ...

uctypes: Any
