from typing import Any

class DecompIO:
    def __init__(self, *args: Any) -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def readline() -> None: ...

def decompress() -> None: ...
