from typing import Any

async def wait_for(aw: Any, timeout: Any, sleep: Any=...) -> Any: ...
def wait_for_ms(aw: Any, timeout: Any) -> Any: ...
async def gather(*aws: Any, return_exceptions: bool=...) -> Any: ...
