from typing import Any

class Lock:
    state: int = ...
    waiting: Any = ...
    def __init__(self) -> None: ...
    def locked(self) -> None: ...
    def release(self) -> None: ...
    async def acquire(self) -> None: ...
    async def __aenter__(self) -> None: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> Any: ...
