from typing import Any

class Chunk:
    def __init__(self, *args: Any) -> None: ...
    def close() -> None: ...
    def getname() -> None: ...
    def getsize() -> None: ...
    def isatty() -> None: ...
    def read() -> None: ...
    def seek() -> None: ...
    def skip() -> None: ...
    def tell() -> None: ...
