from typing import Any

class Emoji:
    def __init__(self, *args: Any) -> None: ...
    def clear() -> None: ...
    def draw_square() -> None: ...
    def show_love() -> None: ...
    def show_map() -> None: ...
    def show_normal() -> None: ...

lcd: Any

def sleep() -> None: ...
