from typing import Any

class MState:
    def __init__(self, *args: Any) -> None: ...
    def end() -> None: ...
    def loop() -> None: ...
    def start() -> None: ...

class MStateManager:
    def __init__(self, *args: Any) -> None: ...
    def change() -> None: ...
    def nextState() -> None: ...
    def register() -> None: ...
    def run() -> None: ...
    def start() -> None: ...
    def stop() -> None: ...
    def unregister() -> None: ...

gc: Any
utime: Any
