from . import simple
from typing import Any

class MQTTClient(simple.MQTTClient):
    DELAY: int = ...
    DEBUG: bool = ...
    def delay(self, i: Any) -> None: ...
    def log(self, in_reconnect: Any, e: Any) -> None: ...
    def reconnect(self): ...
    def publish(self, topic: Any, msg: Any, retain: bool = ..., qos: int = ...): ...
    def wait_msg(self): ...
