from typing import Any

class CancelledError: ...

DEBUG: int

class EventLoop:
    def __init__(self, *args: Any) -> None: ...
    def call_at_() -> None: ...
    def call_later() -> None: ...
    def call_later_ms() -> None: ...
    def call_soon() -> None: ...
    def close() -> None: ...
    def create_task() -> None: ...
    def run_forever() -> None: ...
    def run_until_complete() -> None: ...
    def stop() -> None: ...
    def time() -> None: ...
    def wait() -> None: ...

class IORead:
    def __init__(self, *args: Any) -> None: ...
    def handle() -> None: ...

class IOReadDone:
    def __init__(self, *args: Any) -> None: ...
    def handle() -> None: ...

class IOWrite:
    def __init__(self, *args: Any) -> None: ...
    def handle() -> None: ...

class IOWriteDone:
    def __init__(self, *args: Any) -> None: ...
    def handle() -> None: ...

class SleepMs:
    def __init__(self, *args: Any) -> None: ...
    def handle() -> None: ...

class StopLoop:
    def __init__(self, *args: Any) -> None: ...
    def handle() -> None: ...

class SysCall:
    def __init__(self, *args: Any) -> None: ...
    def handle() -> None: ...

class SysCall1:
    def __init__(self, *args: Any) -> None: ...
    def handle() -> None: ...

def Task() -> None: ...

class TimeoutError: ...

class TimeoutObj:
    def __init__(self, *args: Any) -> None: ...

_event_loop: Any

class _event_loop_class:
    def __init__(self, *args: Any) -> None: ...
    def add_reader() -> None: ...
    def add_writer() -> None: ...
    def call_at_() -> None: ...
    def call_later() -> None: ...
    def call_later_ms() -> None: ...
    def call_soon() -> None: ...
    def close() -> None: ...
    def create_task() -> None: ...
    def remove_reader() -> None: ...
    def remove_writer() -> None: ...
    def run_forever() -> None: ...
    def run_until_complete() -> None: ...
    def stop() -> None: ...
    def time() -> None: ...
    def wait() -> None: ...

_stop_iter: Any

def cancel() -> None: ...
def coroutine() -> None: ...
def ensure_future() -> None: ...
def get_event_loop() -> None: ...

log: Any

def set_debug() -> None: ...

sleep: Any
sleep_ms: Any
time: Any

class type_gen:
    def __init__(self, *args: Any) -> None: ...
    def close() -> None: ...
    def pend_throw() -> None: ...
    def send() -> None: ...
    def throw() -> None: ...

ucollections: Any
utimeq: Any

def wait_for() -> None: ...

wait_for_ms: Any
