from typing import Any

version: str

def height() -> None: ...
def max_width() -> None: ...
def hmap() -> None: ...
def reverse() -> None: ...
def monospaced() -> None: ...
def min_ch() -> None: ...
def max_ch() -> None: ...

_font: bytes
_index: bytes
_mvfont: Any

def _chr_addr(ordch: Any) -> Any: ...
def get_ch(ch: Any) -> Any: ...
