from typing import Any, Optional

def partial(func: Any, *args: Any, **kwargs: Any) -> Any: ...
def update_wrapper(wrapper: Any, wrapped: Any) -> Any: ...
def wraps(wrapped: Any) -> Any: ...
def reduce(function: Any, iterable: Any, initializer: Optional[Any]=...) -> Any: ...
