from typing import Any, Optional

__version__: str

class MPU9250:
    mpu6500: Any = ...
    ak8963: Any = ...
    def __init__(self, i2c: Any, mpu6500: Optional[Any]=..., ak8963: Optional[Any]=...) -> None: ...
    @property
    def acceleration(self) -> None: ...
    @property
    def gyro(self) -> None: ...
    @property
    def magnetic(self) -> None: ...
    @property
    def whoami(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exception_type: Any, exception_value: Any, traceback: Any) -> None: ...
