from typing import Any, Optional

class Editor:
    KEYMAP: Any = ...
    yank_buffer: Any = ...
    find_pattern: str = ...
    case: str = ...
    replc_pattern: str = ...
    top_line: int = ...
    tab_size: Any = ...
    changed: str = ...
    message: str = ...
    content: Any = ...
    undo: Any = ...
    undo_limit: Any = ...
    undo_zero: int = ...
    autoindent: str = ...
    mark: Any = ...
    write_tabs: str = ...
    def __init__(self, tab_size: Any, undo_limit: Any) -> None: ...
    def wr(self, s: Any) -> None: ...
    def rd_any(self) -> None: ...
    def rd(self) -> None: ...
    def goto(self, row: Any, col: Any) -> None: ...
    def clear_to_eol(self) -> None: ...
    def cursor(self, onoff: Any) -> None: ...
    def hilite(self, mode: Any) -> None: ...
    def mouse_reporting(self, onoff: Any) -> None: ...
    def scroll_region(self, stop: Any) -> None: ...
    def scroll_up(self, scrolling: Any) -> None: ...
    def scroll_down(self, scrolling: Any) -> None: ...
    def get_screen_size(self) -> None: ...
    row: Any = ...
    def redraw(self, flag: Any) -> None: ...
    def get_input(self) -> None: ...
    cur_line: Any = ...
    col: Any = ...
    margin: Any = ...
    def display_window(self) -> None: ...
    def spaces(self, line: Any, pos: Optional[Any]=...) -> Any: ...
    def line_range(self) -> None: ...
    def line_edit(self, prompt: Any, default: Any) -> Any: ...
    def find_in_file(self, pattern: Any, col: Any, end: Any) -> Any: ...
    def undo_add(self, lnum: Any, text: Any, key: Any, span: int=...) -> None: ...
    total_lines: Any = ...
    def delete_lines(self, yank: Any) -> None: ...
    fname: Any = ...
    def handle_edit_keys(self, key: Any, char: Any) -> Any: ...
    def edit_loop(self) -> None: ...
    def packtabs(self, s: Any) -> Any: ...
    def get_file(self, fname: Any) -> None: ...
    def put_file(self, fname: Any) -> None: ...

def expandtabs(s: Any) -> Any: ...
def pye(*content: Any, tab_size: int=..., undo: int=..., device: int=..., baud: int=...) -> Any: ...
