import os
from typing import Any

class LS:
    def __repr__(self) -> None: ...
    def __call__(self, path: str=...) -> None: ...

class PWD:
    def __repr__(self) -> None: ...
    def __call__(self) -> None: ...

class CLEAR:
    def __repr__(self) -> None: ...
    def __call__(self) -> None: ...

class CP:
    def __repr__(self) -> None: ...
    def __call__(self, srcf: Any, destf: Any) -> None: ...

pwd: Any
ls: Any
clear: Any
cp: Any
cd = os.chdir
mkdir = os.mkdir
mv = os.rename
rm = os.remove
rmdir = os.rmdir

def head(f: Any, n: int=...) -> None: ...
def cat(f: Any) -> None: ...
def newfile(path: Any) -> None: ...

class Man:
    def __repr__(self) -> None: ...

man: Any
