from typing import Any

class Writer:
    text_row: int = ...
    text_col: int = ...
    row_clip: bool = ...
    col_clip: bool = ...
    @classmethod
    def set_textpos(cls: Any, row: Any, col: Any) -> None: ...
    @classmethod
    def set_clip(cls: Any, row_clip: Any, col_clip: Any) -> None: ...
    device: Any = ...
    font: Any = ...
    map: Any = ...
    screenwidth: Any = ...
    screenheight: Any = ...
    def __init__(self, device: Any, font: Any, verbose: bool=...) -> None: ...
    def _newline(self) -> None: ...
    def printstring(self, string: Any) -> None: ...
    def _printchar(self, char: Any) -> None: ...
    def _printchar_bitwise(self, char: Any) -> None: ...
