from typing import Any

CONFIG: Any
EN_RXADDR: Any
SETUP_AW: Any
SETUP_RETR: Any
RF_CH: Any
RF_SETUP: Any
STATUS: Any
RX_ADDR_P0: Any
TX_ADDR: Any
RX_PW_P0: Any
FIFO_STATUS: Any
DYNPD: Any
EN_CRC: Any
CRCO: Any
PWR_UP: Any
PRIM_RX: Any
POWER_0: Any
POWER_1: Any
POWER_2: Any
POWER_3: Any
SPEED_1M: Any
SPEED_2M: Any
SPEED_250K: Any
RX_DR: Any
TX_DS: Any
MAX_RT: Any
RX_EMPTY: Any
R_RX_PL_WID: Any
R_RX_PAYLOAD: Any
W_TX_PAYLOAD: Any
FLUSH_TX: Any
FLUSH_RX: Any
NOP: Any

class NRF24L01:
    buf: Any = ...
    spi: Any = ...
    cs: Any = ...
    ce: Any = ...
    payload_size: Any = ...
    pipe0_read_addr: Any = ...
    def __init__(self, spi: Any, cs: Any, ce: Any, channel: int=..., payload_size: int=...) -> None: ...
    def init_spi(self, baudrate: Any) -> None: ...
    def reg_read(self, reg: Any) -> Any: ...
    def reg_write_bytes(self, reg: Any, buf: Any) -> Any: ...
    def reg_write(self, reg: Any, value: Any) -> Any: ...
    def flush_rx(self) -> None: ...
    def flush_tx(self) -> None: ...
    def set_power_speed(self, power: Any, speed: Any) -> None: ...
    def set_crc(self, length: Any) -> None: ...
    def set_channel(self, channel: Any) -> None: ...
    def open_tx_pipe(self, address: Any) -> None: ...
    def open_rx_pipe(self, pipe_id: Any, address: Any) -> None: ...
    def start_listening(self) -> None: ...
    def stop_listening(self) -> None: ...
    def any(self) -> None: ...
    def recv(self) -> None: ...
    def send(self, buf: Any, timeout: int=...) -> None: ...
    def send_start(self, buf: Any) -> None: ...
    def send_done(self) -> None: ...
