from typing import Any

_CMD_TIMEOUT: Any
_R1_IDLE_STATE: Any
_R1_ILLEGAL_COMMAND: Any
_TOKEN_CMD25: Any
_TOKEN_STOP_TRAN: Any
_TOKEN_DATA: Any

class SDCard:
    spi: Any = ...
    cs: Any = ...
    cmdbuf: Any = ...
    dummybuf: Any = ...
    tokenbuf: Any = ...
    dummybuf_memoryview: Any = ...
    def __init__(self, spi: Any, cs: Any) -> None: ...
    def init_spi(self, baudrate: Any) -> None: ...
    sectors: Any = ...
    def init_card(self) -> None: ...
    cdv: int = ...
    def init_card_v1(self) -> None: ...
    def init_card_v2(self) -> None: ...
    def cmd(self, cmd: Any, arg: Any, crc: Any, final: int=..., release: bool=..., skip1: bool=...) -> Any: ...
    def readinto(self, buf: Any) -> None: ...
    def write(self, token: Any, buf: Any) -> None: ...
    def write_token(self, token: Any) -> None: ...
    def readblocks(self, block_num: Any, buf: Any) -> None: ...
    def writeblocks(self, block_num: Any, buf: Any) -> None: ...
    def ioctl(self, op: Any, arg: Any) -> Any: ...
