from typing import Any

class deque:
    maxlen: Any = ...
    flags: Any = ...
    d: Any = ...
    def __init__(self, iterable: Any, maxlen: Any, flags: int=...) -> None: ...
    def __len__(self) -> None: ...
    def append(self, x: Any) -> None: ...
    def popleft(self) -> None: ...
