from typing import Any, Optional

class _hash:
    _: Any = ...
    def __init__(self, data: Optional[Any]=...) -> None: ...
    def update(self, data: Any) -> None: ...
    def digest(self) -> None: ...

class md5(_hash): ...
class sha1(_hash): ...
class sha256(_hash): ...
