import io
from typing import Any, Optional

class UioStream:
    _s: Any = ...
    _is_bin: Any = ...
    def __init__(self, s: Any, is_bin: Any) -> None: ...
    def write(self, data: Any, off: Optional[Any]=..., sz: Optional[Any]=...) -> None: ...
    def __getattr__(self, attr: Any) -> Any: ...
    def __iter__(self) -> Any: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> Any: ...

class StringIO(io.StringIO):
    def __iadd__(self, s: Any) -> Any: ...

class BytesIO(io.BytesIO):
    def __iadd__(self, s: Any) -> Any: ...

def open(name: Any, mode: str=..., *args: Any, **kw: Any) -> Any: ...
