from typing import Any

MICROPY_PY_UTIME_TICKS_PERIOD: Any
_PASSTHRU: Any
clock: Any

def sleep_ms(t: Any) -> None: ...
def sleep_us(t: Any) -> None: ...
def ticks_ms() -> None: ...
def ticks_us() -> None: ...
ticks_cpu = ticks_us

def ticks_add(t: Any, delta: Any) -> Any: ...
def ticks_diff(a: Any, b: Any) -> Any: ...
