from token import *
from typing import Any

COMMENT: Any
NL: Any
ENCODING: Any

class TokenInfo:
    def __str__(self) -> None: ...

def get_indent(l: Any) -> Any: ...
def get_str(l: Any, readline: Any) -> Any: ...
def tokenize(readline: Any) -> None: ...
