from typing import Any

class FlashBdev:
    SEC_SIZE: int = ...
    RESERVED_SECS: int = ...
    START_SEC: Any = ...
    NUM_BLK: Any = ...
    blocks: Any = ...
    def __init__(self, blocks: Any=...) -> None: ...
    def readblocks(self, n: Any, buf: Any) -> None: ...
    def writeblocks(self, n: Any, buf: Any) -> None: ...
    def ioctl(self, op: Any, arg: Any) -> Any: ...

size: Any
bdev: Any
