from typing import Any

ONE_SHOT: int
PERIODIC: int

class Timer:
    def __init__(self, *args: Any) -> None: ...
    ONE_SHOT: int = ...
    PERIODIC: int = ...
    def deinit() -> None: ...
    def init() -> None: ...
    def setCallback() -> None: ...
    def start() -> None: ...
    def stop() -> None: ...
    def update() -> None: ...

machine: Any
time: Any

class timeSch:
    def __init__(self, *args: Any) -> None: ...
    ONE_SHOT: int = ...
    PERIODIC: int = ...
    def checkInit() -> None: ...
    def deinit() -> None: ...
    def event() -> None: ...
    def remove_all() -> None: ...
    def run() -> None: ...
    def setTimer() -> None: ...
    def stop() -> None: ...
    def timerCb() -> None: ...
