from typing import Any

class LockType:
    def __init__(self, *args: Any) -> None: ...
    def acquire() -> None: ...
    def locked() -> None: ...
    def release() -> None: ...

def allocate_lock() -> None: ...
def exit() -> None: ...
def get_ident() -> None: ...
def stack_size() -> None: ...
def start_new_thread() -> None: ...
