from typing import Any

class MutableMapping:
    def __init__(self, *args: Any) -> None: ...

class OrderedDict:
    def __init__(self, *args: Any) -> None: ...
    def clear() -> None: ...
    def copy() -> None: ...
    def fromkeys() -> None: ...
    def get() -> None: ...
    def items() -> None: ...
    def keys() -> None: ...
    def pop() -> None: ...
    def popitem() -> None: ...
    def setdefault() -> None: ...
    def update() -> None: ...
    def values() -> None: ...

class defaultdict:
    def __init__(self, *args: Any) -> None: ...

class deque:
    def __init__(self, *args: Any) -> None: ...
    def append() -> None: ...
    def appendleft() -> None: ...
    def extend() -> None: ...
    def pop() -> None: ...
    def popleft() -> None: ...
    def popright() -> None: ...

def namedtuple() -> None: ...
