from typing import Any

class Button:
    def __init__(self, *args: Any) -> None: ...
    BEACON: int = ...
    CENTER: int = ...
    DOWN: int = ...
    LEFT: int = ...
    LEFT_DOWN: int = ...
    LEFT_UP: int = ...
    RIGHT: int = ...
    RIGHT_DOWN: int = ...
    RIGHT_UP: int = ...
    UP: int = ...

class Color:
    def __init__(self, *args: Any) -> None: ...
    BLACK: int = ...
    BLUE: int = ...
    BROWN: int = ...
    GREEN: int = ...
    ORANGE: int = ...
    PURPLE: int = ...
    RED: int = ...
    WHITE: int = ...
    YELLOW: int = ...

class Direction:
    def __init__(self, *args: Any) -> None: ...
    CLOCKWISE: int = ...
    COUNTERCLOCKWISE: int = ...

class Port:
    def __init__(self, *args: Any) -> None: ...
    A: int = ...
    B: int = ...
    C: int = ...
    D: int = ...
    S1: int = ...
    S2: int = ...
    S3: int = ...
    S4: int = ...

class Stop:
    def __init__(self, *args: Any) -> None: ...
    BRAKE: int = ...
    COAST: int = ...
    HOLD: int = ...
