from typing import Any

class Struct:
    def __init__(self, *args: Any) -> None: ...
    def pack() -> None: ...
    def unpack() -> None: ...

def calcsize() -> None: ...
def pack() -> None: ...
def pack_into() -> None: ...
def unpack() -> None: ...
def unpack_from() -> None: ...
