from typing import Any

class StopWatch:
    def __init__(self, *args: Any) -> None: ...
    def pause() -> None: ...
    def reset() -> None: ...
    def resume() -> None: ...
    def time() -> None: ...

def wait() -> None: ...
