from typing import Any

class websocket:
    def __init__(self, *args: Any) -> None: ...
    def close() -> None: ...
    def ioctl() -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def readline() -> None: ...
    def write() -> None: ...
