from typing import Any

class Event:
    def clear(self) -> Any: ...
    def is_set(self) -> Any: ...
    def set(self) -> Any: ...
    wait: Any = ...

class ThreadSafeFlag:
    def ioctl(self) -> Any: ...
    def set(self) -> Any: ...
    wait: Any = ...
core = Any
uio = Any
