from typing import Any

class Server:
    _serve: Any = ...
    def close(self) -> Any: ...
    wait_closed: Any = ...

class Stream:
    aclose: Any = ...
    awrite: Any = ...
    awritestr: Any = ...
    def close(self) -> Any: ...
    drain: Any = ...
    def get_extra_info(self) -> Any: ...
    read: Any = ...
    readexactly: Any = ...
    readline: Any = ...
    wait_closed: Any = ...
    def write(self) -> Any: ...

class StreamReader:
    aclose: Any = ...
    awrite: Any = ...
    awritestr: Any = ...
    def close(self) -> Any: ...
    drain: Any = ...
    def get_extra_info(self) -> Any: ...
    read: Any = ...
    readexactly: Any = ...
    readline: Any = ...
    wait_closed: Any = ...
    def write(self) -> Any: ...

class StreamWriter:
    aclose: Any = ...
    awrite: Any = ...
    awritestr: Any = ...
    def close(self) -> Any: ...
    drain: Any = ...
    def get_extra_info(self) -> Any: ...
    read: Any = ...
    readexactly: Any = ...
    readline: Any = ...
    wait_closed: Any = ...
    def write(self) -> Any: ...
core = Any
open_connection = Any
start_server = Any
stream_awrite = Any
