from typing import Any

RC: str
CONFIG: str

def input_choice(prompt: Any, choices: Any) -> Any: ...
def getpass(prompt: Any) -> Any: ...
def input_pass() -> None: ...
def exists(fname: Any) -> Any: ...
def copy_stream(s_in: Any, s_out: Any) -> None: ...
def get_daemon_status() -> None: ...
def add_daemon() -> None: ...
def change_daemon(action: Any) -> None: ...
def main() -> None: ...
