from typing import Any

def get_lcd(lcd: Any) -> Any: ...
def show_adc(lcd: Any, adc: Any) -> None: ...
def test_features(lcd: Any, orient: Any=...) -> None: ...
def test_mandel(lcd: Any, orient: Any=...) -> Any: ...
def test_all(lcd: Any, orient: Any=...) -> None: ...
