from typing import Any

class Align:
    def __init__(self, *args: Any) -> None: ...
    BOTTOM: int = ...
    BOTTOM_LEFT: int = ...
    BOTTOM_RIGHT: int = ...
    CENTER: int = ...
    LEFT: int = ...
    RIGHT: int = ...
    TOP: int = ...
    TOP_LEFT: int = ...
    TOP_RIGHT: int = ...

class Display:
    def __init__(self, *args: Any) -> None: ...
    _font_height: int = ...
    def _next_line() -> None: ...
    def _reset_text_history() -> None: ...
    _valid_devices: Any = ...
    def clear() -> None: ...
    def image() -> None: ...
    def text() -> None: ...

class Ev3devDisplay:
    def __init__(self, *args: Any) -> None: ...
    def image() -> None: ...
    def reset_screen() -> None: ...
    def scroll() -> None: ...
    def text_grid() -> None: ...
    def text_pixels() -> None: ...

class ImageFile:
    def __init__(self, *args: Any) -> None: ...

path: Any
