from typing import Any

class DriveBase:
    def __init__(self, *args: Any) -> None: ...
    def drive() -> None: ...
    def drive_time() -> None: ...
    def stop() -> None: ...

class Stop:
    def __init__(self, *args: Any) -> None: ...
    BRAKE: int = ...
    COAST: int = ...
    HOLD: int = ...

pi: float

def wait() -> None: ...
