from typing import Any, Optional

TAR_HEADER: Any
DIRTYPE: str
REGTYPE: str

def roundup(val: Any, align: Any) -> Any: ...

class FileSection:
    f: Any = ...
    content_len: Any = ...
    align: Any = ...
    def __init__(self, f: Any, content_len: Any, aligned_len: Any) -> None: ...
    def read(self, sz: int=...) -> Any: ...
    def readinto(self, buf: Any) -> Any: ...
    def skip(self) -> None: ...

class TarInfo:
    def __str__(self) -> None: ...

class TarFile:
    f: Any = ...
    subf: Any = ...
    def __init__(self, name: Optional[Any]=..., fileobj: Optional[Any]=...) -> None: ...
    def next(self) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> None: ...
    def extractfile(self, tarinfo: Any) -> Any: ...
