from typing import Any, Optional

class Response:
    raw: Any = ...
    encoding: str = ...
    _cached: Any = ...
    def __init__(self, f: Any) -> None: ...
    def close(self) -> None: ...
    @property
    def content(self) -> None: ...
    @property
    def text(self) -> None: ...
    def json(self) -> None: ...

def request(method: Any, url: Any, data: Optional[Any]=..., json: Optional[Any]=..., headers: Any=..., stream: Optional[Any]=...) -> Any: ...
def head(url: Any, **kw: Any) -> Any: ...
def get(url: Any, **kw: Any) -> Any: ...
def post(url: Any, **kw: Any) -> Any: ...
def put(url: Any, **kw: Any) -> Any: ...
def patch(url: Any, **kw: Any) -> Any: ...
def delete(url: Any, **kw: Any) -> Any: ...
