from typing import Any

class Dac:
    def __init__(self, *args: Any) -> None: ...
    WRITE: int = ...
    WRITE_EEPROM: int = ...
    def _available() -> None: ...
    def deinit() -> None: ...
    portMethod: int = ...
    def setVoltage() -> None: ...
    def writeData() -> None: ...

def const() -> None: ...

i2c_bus: Any
unit: Any
