from typing import Any

class Ext_io:
    def __init__(self, *args: Any) -> None: ...
    ALL_INPUT: int = ...
    ALL_OUTPUT: int = ...
    INPUT: int = ...
    OUTPUT: int = ...
    def _available() -> None: ...
    def _get_mode() -> None: ...
    def deinit() -> None: ...
    def digitRead() -> None: ...
    def digitReadPort() -> None: ...
    def digitWrite() -> None: ...
    def digitWritePort() -> None: ...
    def setPinMode() -> None: ...
    def setPortMode() -> None: ...

def const() -> None: ...

i2c_bus: Any
unit: Any
ustruct: Any
