from typing import Any

class Ncir:
    def __init__(self, *args: Any) -> None: ...
    def _available() -> None: ...
    def deinit() -> None: ...
    temperature: Any = ...

def const() -> None: ...

i2c_bus: Any
unit: Any
ustruct: Any
