from typing import Any

class Pahub:
    def __init__(self, *args: Any) -> None: ...
    def _available() -> None: ...
    def deinit() -> None: ...
    def select() -> None: ...
    def select_only_on() -> None: ...
    def select_port() -> None: ...

i2c_bus: Any
unit: Any
