from typing import Any

class Tracker:
    def __init__(self, *args: Any) -> None: ...
    def _available() -> None: ...
    def _register_char() -> None: ...
    def _register_short() -> None: ...
    def deinit() -> None: ...
    def getAnalogValue() -> None: ...
    def getDigitalValue() -> None: ...
    def setAnalogValue() -> None: ...

i2c_bus: Any
unit: Any
ustruct: Any
