from typing import Any

ARRAY: int
SOCK_STREAM: int
UINT16: int
UINT8: int
_thread: Any

def addressof() -> None: ...
def sizeof() -> None: ...

class socket:
    def __init__(self, *args: Any) -> None: ...
    def accept() -> None: ...
    def bind() -> None: ...
    def close() -> None: ...
    def connect() -> None: ...
    def fileno() -> None: ...
    def listen() -> None: ...
    def makefile() -> None: ...
    def read() -> None: ...
    def readinto() -> None: ...
    def readline() -> None: ...
    def recv() -> None: ...
    def recvfrom() -> None: ...
    def send() -> None: ...
    def sendto() -> None: ...
    def setblocking() -> None: ...
    def setsockopt() -> None: ...
    def write() -> None: ...

class struct:
    def __init__(self, *args: Any) -> None: ...

time: Any
